name: Deploy Web Assets to Supabase Storage

on:
  workflow_run:
    workflows: ["Run Jest Tests", "Run pnpm scratch"]
    branches: [main, develop]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if the triggering workflow completed successfully
    if: github.event.workflow_run.conclusion == 'success'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build web application
        run: pnpm build --filter=@zygo/web
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        
      - name: Deploy to Supabase Storage
        run: |
          # Create storage bucket if it doesn't exist
          supabase storage create web-assets --public || true
          
          # Upload built assets to storage
          find apps/web/dist -type f -name "*.html" -o -name "*.js" -o -name "*.css" -o -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.svg" -o -name "*.ico" -o -name "*.woff" -o -name "*.woff2" -o -name "*.ttf" | while read file; do
            # Get relative path from dist directory
            relative_path=${file#apps/web/dist/}
            echo "Uploading $file to $relative_path"
            supabase storage upload web-assets "$relative_path" "$file" --upsert
          done
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}